# Extra config for local debugging. Apply with:
#   west build -b nrf5340dk/nrf5340/cpuapp . -- -DEXTRA_CONF_FILE="debug-overlay.conf"

# General
CONFIG_DEBUG=y
CONFIG_DEBUG_OPTIMIZATIONS=y
CONFIG_DEBUG_THREAD_INFO=y
CONFIG_STACK_USAGE=y
CONFIG_STACK_SENTINEL=y
CONFIG_INIT_STACKS=y

# Verbose logging
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_BUFFER_SIZE=4096
